param(
  [string]$Source = "promo.html",
  [string]$Output = "artifacts/promo-16x9.mp4",
  [double]$Duration = 0,
  [int]$Fps = 30,
  [string]$MusicPath = "",
  [string]$MusicSourceUrl = "",
  [string]$MusicLicense = "",
  [string]$MusicCredit = "",
  [string]$CueTimes = "",
  [switch]$Publishable,
  [switch]$SkipFrameRender
)

$ErrorActionPreference = "Stop"
$sourcePath = [System.IO.Path]::GetFullPath($Source)
$outputPath = [System.IO.Path]::GetFullPath($Output)
$projectRoot = Split-Path -Parent $sourcePath
$frames = Join-Path $projectRoot "artifacts\promo-frames"
$temporaryBed = Join-Path $projectRoot "artifacts\temporary-original-bed.wav"
$attributionPath = [System.IO.Path]::ChangeExtension($outputPath, ".audio.md")
$manifestPath = [System.IO.Path]::ChangeExtension($outputPath, ".render.json")
$renderer = Join-Path $PSScriptRoot "render_frames.mjs"

$sourceMarkup = Get-Content -LiteralPath $sourcePath -Raw -Encoding UTF8
$metadataMatch = [regex]::Match($sourceMarkup, '(?s)<script id="promo-metadata" type="application/json">\s*(\{.*?\})\s*</script>')
$metadata = if ($metadataMatch.Success) { $metadataMatch.Groups[1].Value | ConvertFrom-Json } else { $null }
if ($Duration -le 0) { $Duration = if ($metadata -and $metadata.duration) { [double]$metadata.duration } else { 31.2 } }
if ([string]::IsNullOrWhiteSpace($CueTimes)) {
  $CueTimes = if ($metadata -and $metadata.cues) {
    (($metadata.cues.PSObject.Properties | ForEach-Object { [string]$_.Value }) -join ',')
  } else { "5.05,6.95,12.00,14.80,20.15,26.90" }
}

function Find-Tool([string]$Name, [string[]]$Fallbacks) {
  $command = Get-Command $Name -ErrorAction SilentlyContinue
  if ($command) { return $command.Source }
  foreach ($candidate in $Fallbacks) { if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate } }
  throw "Required tool not found: $Name"
}

$node = Find-Tool "node" @(
  (Join-Path $env:USERPROFILE ".cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe")
)
$ffmpeg = Find-Tool "ffmpeg" @("D:\Program Files\ffmpeg\bin\ffmpeg.exe")
foreach ($required in @($sourcePath, $renderer)) { if (!(Test-Path -LiteralPath $required)) { throw "Missing source: $required" } }
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $outputPath), (Split-Path -Parent $temporaryBed) | Out-Null

if (!$SkipFrameRender) {
  & $node $renderer --source $sourcePath --frames $frames --fps $Fps --duration $Duration
  if ($LASTEXITCODE -ne 0) { throw "Frame rendering failed with exit code $LASTEXITCODE" }
}

if ([string]::IsNullOrWhiteSpace($MusicPath)) {
  if ($Publishable) { throw "Publishable renders require MusicPath and complete music attribution" }
  Write-Warning "No licensed music supplied. Using a deterministic temporary ambient bed; replace it before public release unless accepted by the user."
  $bed = "aevalsrc=0.018*(sin(2*PI*110*t)+0.55*sin(2*PI*220*t)+0.35*sin(2*PI*277.18*t)+0.25*sin(2*PI*329.63*t))*(0.72+0.28*sin(2*PI*0.125*t)):s=48000:d=$Duration"
  & $ffmpeg -y -f lavfi -i $bed -af "afade=t=in:st=0:d=0.8,afade=t=out:st=$($Duration-1.2):d=1.2" -c:a pcm_s16le $temporaryBed
  if ($LASTEXITCODE -ne 0) { throw "Temporary audio generation failed with exit code $LASTEXITCODE" }
  $music = $temporaryBed
  $attribution = @"
# Audio attribution

- Status: review cut only
- Source: procedurally generated by render_video.ps1; no external recording used
- License: not supplied or approved for public release
- Action: replace with approved music, or obtain explicit user approval for this synthetic placeholder bed
"@
} else {
  $music = [System.IO.Path]::GetFullPath($MusicPath)
  if (!(Test-Path -LiteralPath $music)) { throw "Music file does not exist: $music" }
  if ([string]::IsNullOrWhiteSpace($MusicSourceUrl) -or [string]::IsNullOrWhiteSpace($MusicLicense) -or [string]::IsNullOrWhiteSpace($MusicCredit)) {
    throw "MusicSourceUrl, MusicLicense, and MusicCredit are required when MusicPath is supplied"
  }
  $attribution = @"
# Audio attribution

- File: $music
- Source URL: $MusicSourceUrl
- License: $MusicLicense
- Credit: $MusicCredit
"@
}

$cueValues = @($CueTimes.Split(",", [System.StringSplitOptions]::RemoveEmptyEntries) | ForEach-Object { [double]$_.Trim() } | Where-Object { $_ -ge 0 -and $_ -lt $Duration })
$arguments = [System.Collections.Generic.List[string]]::new()
$arguments.AddRange([string[]]@("-y", "-framerate", "$Fps", "-i", (Join-Path $frames "frame-%05d.jpg"), "-i", $music))
$filters = [System.Collections.Generic.List[string]]::new()
$filters.Add("[1:a]apad,atrim=0:$Duration,asetpts=PTS-STARTPTS,volume=0.68,afade=t=in:st=0:d=0.4,afade=t=out:st=$($Duration-1.2):d=1.2[music]")
$mixLabels = [System.Collections.Generic.List[string]]::new()
$mixLabels.Add("[music]")

for ($index = 0; $index -lt $cueValues.Count; $index += 1) {
  $frequency = @(920, 640, 780, 560, 880, 480)[$index % 6]
  $arguments.AddRange([string[]]@("-f", "lavfi", "-i", "sine=frequency=$frequency`:sample_rate=48000`:duration=0.09"))
  $inputIndex = $index + 2
  $delay = [int][Math]::Round($cueValues[$index] * 1000)
  $label = "cue$index"
  $filters.Add("[$inputIndex`:a]volume=0.075,afade=t=out:st=0.05:d=0.04,adelay=$delay|$delay[$label]")
  $mixLabels.Add("[$label]")
}

$filters.Add("$($mixLabels -join '')amix=inputs=$($mixLabels.Count):normalize=0,alimiter=limit=.92[a]")
$arguments.AddRange([string[]]@(
  "-filter_complex", ($filters -join ";"),
  "-map", "0:v:0", "-map", "[a]",
  "-t", "$Duration", "-r", "$Fps",
  "-vf", "scale=in_range=full:out_range=tv,format=yuv420p",
  "-c:v", "libx264", "-profile:v", "high", "-level", "4.1", "-pix_fmt", "yuv420p", "-color_range", "tv", "-crf", "17", "-preset", "medium",
  "-c:a", "aac", "-b:a", "192k", "-ar", "48000", "-movflags", "+faststart",
  $outputPath
))

& $ffmpeg @arguments
if ($LASTEXITCODE -ne 0) { throw "Video encoding failed with exit code $LASTEXITCODE" }
[System.IO.File]::WriteAllText($attributionPath, $attribution.Trim() + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
$manifest = [ordered]@{
  source = $sourcePath
  sourceSha256 = (Get-FileHash -Algorithm SHA256 $sourcePath).Hash
  output = $outputPath
  outputSha256 = (Get-FileHash -Algorithm SHA256 $outputPath).Hash
  duration = $Duration
  fps = $Fps
  cueTimes = $cueValues
  audioAttribution = $attributionPath
  publishable = [bool]$Publishable
  renderedAtUtc = [DateTime]::UtcNow.ToString('o')
}
[System.IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 4) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
Write-Host "Created $outputPath"
Write-Host "Created $attributionPath"
Write-Host "Created $manifestPath"
